// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5LLMMAHcSvw-GAV_VIxF4B4afcMX4Y_0',
    appId: '1:799339038256:web:aeb5e7d72e1c6524cc8ff5',
    messagingSenderId: '799339038256',
    projectId: 'medical-reminder-45ae7',
    authDomain: 'medical-reminder-45ae7.firebaseapp.com',
    storageBucket: 'medical-reminder-45ae7.appspot.com',
    measurementId: 'G-N7F8MEB71V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeb1lWaqhjHGZ2K20Q6J4hnAN4jZvOIAM',
    appId: '1:799339038256:android:0e8d042d349c51cccc8ff5',
    messagingSenderId: '799339038256',
    projectId: 'medical-reminder-45ae7',
    storageBucket: 'medical-reminder-45ae7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKQRa3D9VHWDQzCjNs5pv00p-ZyqtuARU',
    appId: '1:799339038256:ios:f09295079094a2e0cc8ff5',
    messagingSenderId: '799339038256',
    projectId: 'medical-reminder-45ae7',
    storageBucket: 'medical-reminder-45ae7.appspot.com',
    iosClientId:
        '799339038256-hcm9eor34jdcv186pm3dajviunqkog8b.apps.googleusercontent.com',
    iosBundleId: 'com.example.tanyaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKQRa3D9VHWDQzCjNs5pv00p-ZyqtuARU',
    appId: '1:799339038256:ios:f09295079094a2e0cc8ff5',
    messagingSenderId: '799339038256',
    projectId: 'medical-reminder-45ae7',
    storageBucket: 'medical-reminder-45ae7.appspot.com',
    iosClientId:
        '799339038256-hcm9eor34jdcv186pm3dajviunqkog8b.apps.googleusercontent.com',
    iosBundleId: 'com.example.tanyaApp',
  );
}
